### ISSUE TITLE
Deduplication of API requests by allowing to set the outbox record ID

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.TransactionalSession#144]
With the transaction session users still need to write deduplication logic as that is currently not part of the transaction session. It is feature of the outbox itself based on the ID of the outbox record but that ID cannot be set.

I would like to see something like:

```c#
var requestId = context.RequestID;

var session = scope.ServiceProvider.GetRequiredService<ITransactionalSession>();
var exists = await session.Open(
	deduplicationKey: requestId,
	new MyPersistenceOpenSessionOptions(),
	cancellationToken: cancellationToken
	);
	
if(exists)
{
	// Outbox record already exists
	return;
}
```

When committing `.Commit` should NOT fail if the outbox record already exists
```c#
var exists = await session.Commit(cancellationToken);

if(exists)
{
	logger.LogDebug("Commit failed because outbox record already existed thus rolling back DB transaction but continuing as this means the API request was already processed succesfully")
}
```

**Comment by danielmarbach** [comment]
I think this is a duplicate of https://github.com/Particular/NServiceBus.TransactionalSession/issues/97

**Comment by ramonsmits** [comment]
- Duplicate of #97
