### ISSUE TITLE
Missing GitHub release for 2.x

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.TransactionalSession#160]
Is it possible to create GitHub release for 2.x of this package, along with issues closed etc? Thanks!

**Comment by cquirosj** [comment]
@pardahlman I see there is a release for [2.0.0 ](https://github.com/Particular/NServiceBus.TransactionalSession/releases/tag/2.0.0) what closed issues are you interested about getting a release for?

**Comment by pardahlman** [comment]
My bad, I some how missed that it existed. Thanks for pointing it out - closing this issue 👍
