### ISSUE TITLE
Reduce resource overhead when no messages are sent

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.TransactionalSession#335]
#### Is your improvement related to a problem? Please describe.

Somewhat similar to the [TxSession with EF sample](https://docs.particular.net/samples/transactional-session/aspnetcore-webapi/), we have to configure our OR mapper to use the transactional session transaction, this happens conceptually similar to the example as part of the invocation pipeline. Since we always require a database session, opening a transactional session is no problem. 

However, the transactional session always creates an outbox entry and sends a control message, which also gets processed and accesses the database again to mark the outbox entry as dispatched, even if there are no messages sent via the transactional session (which is something that is quite common in our use case). Therefore, in cases where we only access the database connection from the transactional session to store data without sending messages, we're paying quite a high price in regards to additional DB requests (at least 2 writes, 1 read) and message operations (at least 1 send, 1 receive) which provide zero value.

#### Describe the suggested solution

It should be fairly easy (TM) to detect that no messages have been sent through the transactional session. In those cases, there shouldn't be any downside in avoiding the control message and the outbox database entry, reducing cost and performance overhead created by the transactional session.
        
#### Describe alternatives you've considered

* We can't reliable predict as part of the "middleware" whether the code being invoked needs to send messages or not, therefore there isn't an easy way to swap the transaction management to something else in such cases. Also, that would require significant complexity and custom code that the the transactional session already does well so we'd like to not re-invent the wheel.

**Comment by tmasternak** [comment]
Thank you for your input Tim, we will consider that in the future platform enhancements work.

**Comment by danielmarbach** [comment]
@timbussmann After discussing the use cases a bit more with some of your colleagues, we have [created an improvement PR that addresses this issue](https://github.com/Particular/NServiceBus.TransactionalSession/pull/348) with a [follow-up PR that will allow opting-out from the deduplication record creation](https://github.com/Particular/NServiceBus.TransactionalSession/pull/349).

Things are still a bit raw and some details need to be figured out, but we wanted to give you a heads-up.

**Comment by timbussmann** [comment]
awesome ❤️

**Comment by danielmarbach** [comment]
@timbussmann we have [released 3.2.0 of the transactional session that implements this improvement](https://discuss.particular.net/t/nservicebus-transactionalsession-3-2-0-minor-release-available/4088)
